#pragma once

#define PHIL_CART_VERSION "0.4.0"

#define PHIL_CART_STRINGIZE_INNER(value) #value
#define PHIL_CART_STRINGIZE(value) PHIL_CART_STRINGIZE_INNER(value)

#ifndef P1AM_OTA_BUILD_TOKEN
#define P1AM_OTA_BUILD_TOKEN dev
#endif

#define P1AM_OTA_BUILD_ID PHIL_CART_STRINGIZE(P1AM_OTA_BUILD_TOKEN)
